LIVE = True
FARMING_TOOL_SPEED_BOOST = 0
LOCATION = 'Celondim'

PROJECT_DIRECTORY = r'C:\Users\Amirf\code\lotro-bot'

IMAGES_DIRECTORY_PATH = PROJECT_DIRECTORY + r'\reference_images'
LOGS_DIRECTORY_PATH = PROJECT_DIRECTORY + r'\logs'
ML_DATA_DIRECTORY_PATH = PROJECT_DIRECTORY + r'\ml_data'
